### ISSUE TITLE
퀴즈 데이터가 안불러와 지는 문제

### ISSUE THREAD

**Issue by bmm522** [bmm522/JobSeeckerStudio#17]
퀴즈 데이터가 안 불러와 지는 문제

quiz-batch에서 redis에 저장하는 작업을 한 스텝 내에서 삭제 ㅡ> 저장하는 것이 아니라 스텝 별로 나눠서 확실히 순서를 보장해야 할 거같음.

**Comment by bmm522** [comment]
저장과 삭제를 한스텝에서 구현했었는데, 각각의 스텝으로 나눈 후 순서 보장하여 해결

**Comment by bmm522** [comment]
여전히 퀴즈 데이터가 제대로 안불러와짐, 레디스 조작 라이브러리를 CrudRepository 에서 RedisTemplate로 변경예정

**Comment by bmm522** [comment]
처음에는 영속성 문제인가 하고 생각했으나, 혹시 몰라서 레디스에 접속중인 클라이언트 리스트를 확인했습니다.

![클라이언트숫자](https://github.com/bmm522/quiz-studio/assets/102157839/88b580ba-9570-44e1-8c48-53e517eee5f7)

그런데 이상하게 3개의 클라이언트 접속이 있어서 해당 리스트를 확인해본 후 해당 ec2 서버가 아닌 못보던 아이피 주소가 있어서 검색을 해봤습니다.

![아이피](https://github.com/bmm522/quiz-studio/assets/102157839/27c133e3-b89c-4c56-8f89-edca7142c96c)

아무리봐도 이상한 ip라고 생각이 들어, 해당 클라이언트 ip를 삭제하려고 시도했지만 계속 생기는 것을 알 수 있었습니다.

![또나타남](https://github.com/bmm522/quiz-studio/assets/102157839/9351f56a-b3a9-4869-978c-e357fdf3e0e6)

![또나타남2](https://github.com/bmm522/quiz-studio/assets/102157839/6a1ea744-b866-4f27-b399-3fb329e23ac7)

레디스의 로그를 살펴보니 지속적으로 init이 실행된 것을 확인할 수 있었습니다.


![로그](https://github.com/bmm522/quiz-studio/assets/102157839/762450ff-8fff-4cee-b2c0-e8fd39f4a555)

해당 레디스 서버를 내리고, 비밀번호 재 설정 후 다시 재가동시켰습니다.

**Comment by quietwave00** [comment]
수고하셨습니다!
